@extends('template/template')
@section('header') 
    @include('pages/header')
@stop
@section('body')
     @include('pages/postular-encargo-error') 
@stop
@section('footer')
    @include('pages/footer') 
@stop