@extends('template/template')
@section('header')
    @include('pages/header')
@stop
@section('body')
     @include('pages/postular-encargo-success') 
@stop
@section('footer')
    @include('pages/footer') 
@stop