@extends('template/template') 
@section('header')
    @include('pages/header')
@stop
@section('body')
     @include('pages/publicar-encargo') 
@stop
@section('footer')
    @include('pages/footer') 
@stop